<?php
declare(strict_types=1);

const APP_VERSION = '0.2.2';
const DEFAULT_MODEL_NAME = 'gemini-2.5-flash';
const MAX_UPLOAD_BYTES = 20 * 1024 * 1024;
const LARGE_PDF_BYTES = 8 * 1024 * 1024;
const LARGE_PDF_PAGE_WARNING_THRESHOLD = 100;
const PDF_SPLIT_MIN_PAGES_PER_PART = 1;
const PDF_SPLIT_MAX_PAGES_PER_PART = 500;
const INGESTION_MAX_OUTPUT_TOKENS = 16384;
const INGESTION_THINKING_BUDGET = 0;
const INGESTION_GEMINI_FALLBACK_MODEL = 'gemini-2.5-flash-lite';
const MAX_TEXT_SOURCE_BYTES = 900000;
const MAX_RETRIEVAL_CHUNKS = 5;
const MAX_PROXY_BODY_BYTES = 128 * 1024;
const MAX_PROXY_QUERY_CHARS = 4000;
const MAX_PROXY_MESSAGE_CHARS = 5000;
const MAX_PROXY_MESSAGES = 20;
const PROXY_RATE_LIMIT_WINDOW_SECONDS = 60;
const PROXY_RATE_LIMIT_MAX_REQUESTS = 30;
